### ISSUE TITLE
Stars landing in 00h:5Xm - 01h:0Xm are detected as landing in 00m-0Xm

### ISSUE THREAD

**Issue by Unmoon** [pwatts6060/Shooting-Stars-Tracking#2]
For example:
![image](https://user-images.githubusercontent.com/7273082/112002330-70a8de80-8b28-11eb-87fe-61d2e5f4e9a1.png)
results in (taken a few minutes after scoping)
![image](https://user-images.githubusercontent.com/7273082/112002418-874f3580-8b28-11eb-8611-0ff379eb019a.png)
but should be like this (taken after the 1 hour mark passed)
![image](https://user-images.githubusercontent.com/7273082/112002502-9fbf5000-8b28-11eb-820f-61011acf561b.png)

**Comment by Navtik** [comment]
A message format I did not encounter. It should now correctly read the 58 mins instead of the 0.
