### ISSUE TITLE
Importing causes severe performance degradation 

### ISSUE THREAD

**Issue by Bram91** [pwatts6060/Shooting-Stars-Tracking#3]
When trying to import a big list the client FPS drops to 1~2fps for about 6 minutes before recovering.

After importing it will instantly report `Imported star data.` to then make the client slow down to a crawl:
![image](https://user-images.githubusercontent.com/7499230/112117689-e447fb80-8bbb-11eb-93ef-9c082d7fd4e5.png)
Attached is a text file containing json data that should reproduce the problem.
[Shooting-Stars-Tracking-JSON.txt](https://github.com/HarveyWilson/Shooting-Stars-Tracking/files/6188066/Shooting-Stars-Tracking-JSON.txt)

**Comment by Navtik** [comment]
Now fixed in the latest version.
It was sorting the list for every star added on the import, it will now update the list after all the stars have been added.
